# Generated by Django 5.1.4 on 2025-03-04 04:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("emp_id", models.CharField(max_length=20)),
                ("is_enabled", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("is_enabled", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OvertimeRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("employee_name", models.CharField(blank=True, max_length=100)),
                ("project_name", models.CharField(blank=True, max_length=50)),
                ("request_date", models.DateField()),
                ("time_start", models.TimeField()),
                ("time_end", models.TimeField()),
                ("total_hours", models.DecimalField(decimal_places=2, max_digits=4)),
                ("has_break", models.BooleanField(default=False)),
                ("break_start", models.TimeField(blank=True, null=True)),
                ("break_end", models.TimeField(blank=True, null=True)),
                ("break_hours", models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ("reason", models.TextField()),
                ("detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_weekend", models.BooleanField(default=False)),
                ("is_holiday", models.BooleanField(default=False)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.employee")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.project")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("event_type", models.CharField(choices=[("holiday", "Holiday"), ("leave", "Leave"), ("meeting", "Meeting"), ("task", "Task")], default="task", max_length=20)),
                ("description", models.TextField(blank=True, null=True)),
                ("start", models.DateTimeField(default=django.utils.timezone.now)),
                ("end", models.DateTimeField(default=django.utils.timezone.now)),
                ("meeting_url", models.URLField(blank=True, null=True)),
                ("agent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="agent_for_leaves", to="api.employee")),
                ("applied_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="leave_applications", to="api.employee")),
                ("assigned_to", models.ManyToManyField(blank=True, related_name="assigned_events", to="api.employee")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="created_events", to="api.employee")),
                ("project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.project")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
