# Generated by Django 5.1.4 on 2025-04-28 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OvertimeBreak",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("duration_hours", models.DecimalField(decimal_places=2, max_digits=4)),
                ("overtime_request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="breaks", to="api.overtimerequest")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
