# Generated by Django 6.0 on 2026-01-08 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_department_and_dept_links"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["emp_id"]},
        ),
        migrations.RenameIndex(
            model_name="employee",
            new_name="api_employe_emp_id_67cac0_idx",
            old_name="api_employee_emp_id_idx",
        ),
        migrations.RenameIndex(
            model_name="employee",
            new_name="api_employe_departm_e0091b_idx",
            old_name="api_employee_department_idx",
        ),
        migrations.RenameIndex(
            model_name="externaluser",
            new_name="external_us_externa_f017d4_idx",
            old_name="external_us_externa_idx",
        ),
        migrations.RenameIndex(
            model_name="externaluser",
            new_name="external_us_usernam_be0f70_idx",
            old_name="external_us_usernam_idx",
        ),
        migrations.RenameIndex(
            model_name="externaluser",
            new_name="external_us_worker__a9d14c_idx",
            old_name="external_us_worker__idx",
        ),
        migrations.RenameIndex(
            model_name="externaluser",
            new_name="external_us_is_acti_bb2544_idx",
            old_name="external_us_is_acti_idx",
        ),
        migrations.RenameIndex(
            model_name="overtimerequest",
            new_name="api_overtim_request_f2c534_idx",
            old_name="api_ot_date_dept_idx",
        ),
        migrations.RenameIndex(
            model_name="overtimerequest",
            new_name="api_overtim_departm_b86c8e_idx",
            old_name="api_ot_dept_code_idx",
        ),
        migrations.RenameIndex(
            model_name="usersession",
            new_name="user_sessio_user_id_bb1b83_idx",
            old_name="user_sessio_user_id_idx",
        ),
        migrations.RenameIndex(
            model_name="usersession",
            new_name="user_sessio_token_e_39c4f6_idx",
            old_name="user_sessio_token_e_idx",
        ),
        migrations.RenameIndex(
            model_name="usersession",
            new_name="user_sessio_last_ac_7cb421_idx",
            old_name="user_sessio_last_ac_idx",
        ),
        migrations.AddField(
            model_name="employee",
            name="exclude_from_reports",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="overtimerequest",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="overtimerequest",
            name="approved_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_overtime_requests", to="api.employee"),
        ),
        migrations.AddField(
            model_name="overtimerequest",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="overtimerequest",
            name="status",
            field=models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], default="pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="department",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="overtimerequest",
            name="department",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="api.department"),
        ),
        migrations.AlterField(
            model_name="overtimerequest",
            name="department_code",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterModelTable(
            name="department",
            table=None,
        ),
    ]
