# Generated by Django 6.0 on 2026-01-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_employee_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OvertimeRegulation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("category", models.CharField(db_index=True, default="general", max_length=50)),
                ("order", models.IntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
                "indexes": [models.Index(fields=["category", "order"], name="api_overtim_categor_9f9a6c_idx"), models.Index(fields=["is_active"], name="api_overtim_is_acti_b629dc_idx")],
            },
        ),
    ]
