# Generated by Django 6.0 on 2026-01-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_overtimeregulation"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="all_day",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="color",
            field=models.CharField(blank=True, help_text="Hex color code (e.g., #FF5733)", max_length=7),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
