# Generated by Django 6.0 on 2026-01-09 03:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_calendarevent_all_day_calendarevent_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OvertimeRegulationDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="Document title", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Document description or notes")),
                ("file", models.FileField(help_text="PDF file only", upload_to="regulations/%Y/%m/", validators=[django.core.validators.FileExtensionValidator(["pdf"])])),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                ("file_hash", models.CharField(blank=True, help_text="SHA256 hash for duplicate detection", max_length=64)),
                ("version", models.IntegerField(default=1, help_text="Version number")),
                ("is_active", models.BooleanField(db_index=True, default=True, help_text="Is current/active version")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, help_text="Soft delete flag")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("smb_path", models.CharField(blank=True, help_text="Path on SMB share if backed up", max_length=500)),
                ("smb_uploaded", models.BooleanField(default=False)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_regulation_documents", to="api.externaluser")),
                ("replaces", models.ForeignKey(blank=True, help_text="Previous version this replaces", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="replaced_by_documents", to="api.overtimeregulationdocument")),
                ("uploaded_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="uploaded_regulation_documents", to="api.externaluser")),
            ],
            options={
                "verbose_name": "Overtime Regulation Document",
                "verbose_name_plural": "Overtime Regulation Documents",
                "db_table": "overtime_regulation_documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["is_active", "is_deleted"], name="overtime_re_is_acti_714b74_idx"),
                    models.Index(fields=["file_hash"], name="overtime_re_file_ha_c5995a_idx"),
                    models.Index(fields=["created_at"], name="overtime_re_created_268874_idx"),
                    models.Index(fields=["uploaded_by"], name="overtime_re_uploade_50cd17_idx"),
                ],
            },
        ),
    ]
