# Generated by Django 6.0 on 2026-01-12 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_calendarevent_leave_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("app_name", models.CharField(default="Overtime Management System", max_length=100)),
                ("app_acronym", models.CharField(default="OMS", max_length=20)),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                ("build_date", models.CharField(default="January 2026", max_length=50)),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configuration",
            },
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="status",
            field=models.CharField(choices=[("todo", "To Do"), ("in_progress", "In Progress"), ("done", "Done")], default="todo", max_length=20),
        ),
        migrations.AddField(
            model_name="externaluser",
            name="menu_permissions",
            field=models.JSONField(blank=True, default=list, help_text="List of allowed menu keys"),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("event", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notifications", to="api.calendarevent")),
                ("recipient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="api.externaluser")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["recipient", "is_read"], name="api_notific_recipie_28b188_idx")],
            },
        ),
    ]
