# Generated by Django 6.0 on 2026-01-12 07:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_systemconfiguration_calendarevent_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["id"]},
        ),
    ]
