# Generated by Django 6.0 on 2026-01-12 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_project_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[("login", "Login"), ("logout", "Logout"), ("create", "Create"), ("update", "Update"), ("delete", "Delete"), ("view", "View"), ("export", "Export")], db_index=True, help_text="Type of action performed", max_length=20
                    ),
                ),
                ("resource", models.CharField(blank=True, help_text="Resource affected (e.g., 'overtime_request', 'employee')", max_length=100, null=True)),
                ("resource_id", models.IntegerField(blank=True, help_text="ID of the affected resource", null=True)),
                ("details", models.JSONField(blank=True, default=dict, help_text="Additional action details")),
                ("ip_address", models.GenericIPAddressField(blank=True, help_text="User's IP address", null=True)),
                ("user_agent", models.TextField(blank=True, help_text="Browser user agent")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True, help_text="When the action occurred")),
                ("user", models.ForeignKey(help_text="User who performed the action", on_delete=django.db.models.deletion.CASCADE, related_name="activity_logs", to="api.externaluser")),
            ],
            options={
                "db_table": "user_activity_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["-timestamp"], name="user_activi_timesta_5d25b4_idx"),
                    models.Index(fields=["user", "-timestamp"], name="user_activi_user_id_0a625a_idx"),
                    models.Index(fields=["action", "-timestamp"], name="user_activi_action_55242b_idx"),
                ],
            },
        ),
    ]
