# Generated by Django 6.0 on 2026-01-13 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_useractivitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="is_repeating",
            field=models.BooleanField(default=False, help_text="Whether this is a repeating event"),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="repeat_frequency",
            field=models.CharField(blank=True, choices=[("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly"), ("yearly", "Yearly")], help_text="How often the event repeats", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="repeat_until",
            field=models.DateTimeField(blank=True, help_text="End date for repeating events", null=True),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="parent_event",
            field=models.ForeignKey(blank=True, help_text="Parent event for repeated occurrences", null=True, on_delete=django.db.models.deletion.CASCADE, related_name="occurrences", to="api.calendarevent"),
        ),
    ]
