# Generated by Django - Task Board Advanced Features
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_calendarevent_priority_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                ("is_edited", models.BooleanField(default=False)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="task_comments", to="api.employee")),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="replies", to="api.taskcomment")),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="api.calendarevent")),
                ("mentions", models.ManyToManyField(blank=True, related_name="mentioned_in_comments", to="api.employee")),
            ],
            options={
                "db_table": "task_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("status_changed", "Status Changed"),
                            ("priority_changed", "Priority Changed"),
                            ("assigned", "Assigned"),
                            ("unassigned", "Unassigned"),
                            ("label_added", "Label Added"),
                            ("label_removed", "Label Removed"),
                            ("comment_added", "Comment Added"),
                            ("due_date_changed", "Due Date Changed"),
                            ("moved", "Moved to Column"),
                        ],
                        max_length=30,
                    ),
                ),
                ("old_value", models.CharField(blank=True, max_length=255, null=True)),
                ("new_value", models.CharField(blank=True, max_length=255, null=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="task_activities", to="api.employee")),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="api.calendarevent")),
            ],
            options={
                "db_table": "task_activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BoardPresence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("channel_name", models.CharField(blank=True, max_length=255)),
                ("editing_task", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="editors", to="api.calendarevent")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="board_presences", to="api.employee")),
            ],
            options={
                "db_table": "board_presence",
            },
        ),
        migrations.AddIndex(
            model_name="taskcomment",
            index=models.Index(fields=["task", "created_at"], name="task_commen_task_id_d4e8f5_idx"),
        ),
        migrations.AddIndex(
            model_name="taskcomment",
            index=models.Index(fields=["author"], name="task_commen_author__6b3c2a_idx"),
        ),
        migrations.AddIndex(
            model_name="taskcomment",
            index=models.Index(fields=["parent"], name="task_commen_parent__f23e1c_idx"),
        ),
        migrations.AddIndex(
            model_name="taskactivity",
            index=models.Index(fields=["task", "-created_at"], name="task_activi_task_id_a1b2c3_idx"),
        ),
        migrations.AddIndex(
            model_name="taskactivity",
            index=models.Index(fields=["actor"], name="task_activi_actor_i_d4e5f6_idx"),
        ),
        migrations.AddIndex(
            model_name="taskactivity",
            index=models.Index(fields=["action"], name="task_activi_action_a7b8c9_idx"),
        ),
        migrations.AddIndex(
            model_name="boardpresence",
            index=models.Index(fields=["user"], name="board_prese_user_id_123abc_idx"),
        ),
        migrations.AddIndex(
            model_name="boardpresence",
            index=models.Index(fields=["last_seen"], name="board_prese_last_se_456def_idx"),
        ),
    ]
