# Generated by Django 6.0 on 2026-01-13 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_taskcomment_taskactivity_boardpresence"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="boardpresence",
            new_name="board_prese_user_id_b2394c_idx",
            old_name="board_prese_user_id_123abc_idx",
        ),
        migrations.RenameIndex(
            model_name="boardpresence",
            new_name="board_prese_last_se_1d2bf3_idx",
            old_name="board_prese_last_se_456def_idx",
        ),
        migrations.RenameIndex(
            model_name="taskactivity",
            new_name="task_activi_task_id_e45ba7_idx",
            old_name="task_activi_task_id_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="taskactivity",
            new_name="task_activi_actor_i_65e48c_idx",
            old_name="task_activi_actor_i_d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="taskactivity",
            new_name="task_activi_action_b4056e_idx",
            old_name="task_activi_action_a7b8c9_idx",
        ),
        migrations.RenameIndex(
            model_name="taskcomment",
            new_name="task_commen_task_id_413a08_idx",
            old_name="task_commen_task_id_d4e8f5_idx",
        ),
        migrations.RenameIndex(
            model_name="taskcomment",
            new_name="task_commen_author__dbe0d1_idx",
            old_name="task_commen_author__6b3c2a_idx",
        ),
        migrations.RenameIndex(
            model_name="taskcomment",
            new_name="task_commen_parent__482dac_idx",
            old_name="task_commen_parent__f23e1c_idx",
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="repeat_until",
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="meeting_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="parent_event",
            field=models.ForeignKey(blank=True, help_text="Parent event for recurring instances", null=True, on_delete=django.db.models.deletion.CASCADE, related_name="child_events", to="api.calendarevent"),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="repeat_frequency",
            field=models.CharField(blank=True, choices=[("hourly", "Every Hour"), ("daily", "Every Day"), ("weekly", "Every Week"), ("monthly", "Every Month"), ("yearly", "Every Year")], help_text="How often the event repeats", max_length=20, null=True),
        ),
    ]
