# Generated by Django 6.0 on 2026-01-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_rename_board_prese_user_id_123abc_idx_board_prese_user_id_b2394c_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaluser",
            name="permission_updated_at",
            field=models.DateTimeField(blank=True, help_text="Timestamp of last permission change, used to force logout", null=True),
        ),
    ]
