# Generated by Django 6.0 on 2026-01-15 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_externaluser_permission_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("color", models.CharField(default="#6366F1", help_text="Group color (hex code)", max_length=7)),
                ("icon", models.CharField(blank=True, help_text="Emoji or icon identifier", max_length=50, null=True)),
                ("is_private", models.BooleanField(default=False, help_text="If true, only members can see tasks in this group")),
                ("order", models.IntegerField(default=0)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="created_task_groups", to="api.externaluser")),
                ("members", models.ManyToManyField(blank=True, related_name="task_groups", to="api.employee")),
            ],
            options={
                "db_table": "task_groups",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="group",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tasks", to="api.taskgroup"),
        ),
        migrations.CreateModel(
            name="TaskReminder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reminder_type",
                    models.CharField(choices=[("15min", "15 minutes before"), ("30min", "30 minutes before"), ("1hour", "1 hour before"), ("2hours", "2 hours before"), ("1day", "1 day before"), ("custom", "Custom time")], default="1hour", max_length=20),
                ),
                ("remind_at", models.DateTimeField(help_text="When to show the reminder")),
                ("message", models.CharField(blank=True, max_length=500, null=True)),
                ("is_triggered", models.BooleanField(default=False, help_text="Whether reminder has been shown")),
                ("is_dismissed", models.BooleanField(default=False, help_text="User dismissed the reminder")),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reminders", to="api.calendarevent")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="task_reminders", to="api.externaluser")),
            ],
            options={
                "db_table": "task_reminders",
                "ordering": ["remind_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeLeave",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(help_text="Date of the leave")),
                ("notes", models.TextField(blank=True, help_text="Optional notes about the leave", null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_employee_leaves", to="api.externaluser")),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="leaves", to="api.employee")),
            ],
            options={
                "ordering": ["date", "employee__name"],
                "indexes": [models.Index(fields=["date"], name="api_employe_date_ad96d4_idx"), models.Index(fields=["employee", "date"], name="api_employe_employe_1b950d_idx")],
                "unique_together": {("employee", "date")},
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="Holiday name/title", max_length=200)),
                ("date", models.DateField(help_text="Date of the holiday")),
                ("color", models.CharField(default="#FFC0CB", help_text="Background color for the holiday (hex code)", max_length=7)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_recurring", models.BooleanField(default=False, help_text="Whether this holiday repeats every year")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_holidays", to="api.externaluser")),
            ],
            options={
                "ordering": ["date"],
                "indexes": [models.Index(fields=["date"], name="api_holiday_date_1a4423_idx")],
                "unique_together": {("title", "date")},
            },
        ),
        migrations.CreateModel(
            name="PersonalNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(blank=True, null=True)),
                ("color", models.CharField(default="#FFEB3B", help_text="Note color (hex code)", max_length=7)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="personal_notes", to="api.externaluser")),
            ],
            options={
                "db_table": "personal_notes",
                "ordering": ["-is_pinned", "order", "-created_at"],
                "indexes": [models.Index(fields=["owner", "-created_at"], name="personal_no_owner_i_011232_idx"), models.Index(fields=["owner", "is_completed"], name="personal_no_owner_i_f60ec0_idx")],
            },
        ),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="task_attachments/%Y/%m/")),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                ("file_type", models.CharField(blank=True, help_text="MIME type", max_length=100)),
                ("description", models.CharField(blank=True, max_length=500, null=True)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="api.calendarevent")),
                ("uploaded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="uploaded_attachments", to="api.employee")),
            ],
            options={
                "db_table": "task_attachments",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["task", "-created_at"], name="task_attach_task_id_5ae3a1_idx")],
            },
        ),
        migrations.AddIndex(
            model_name="taskgroup",
            index=models.Index(fields=["created_by"], name="task_groups_created_a2409c_idx"),
        ),
        migrations.AddIndex(
            model_name="taskreminder",
            index=models.Index(fields=["user", "is_triggered", "remind_at"], name="task_remind_user_id_df4b43_idx"),
        ),
        migrations.AddIndex(
            model_name="taskreminder",
            index=models.Index(fields=["task", "user"], name="task_remind_task_id_fdf921_idx"),
        ),
    ]
