# Generated by Django 6.0 on 2026-01-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_taskgroup_calendarevent_group_taskreminder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeleave",
            name="agent_names",
            field=models.TextField(blank=True, help_text="Comma-separated names of agents not in the employee list", null=True),
        ),
        migrations.AddField(
            model_name="employeeleave",
            name="agents",
            field=models.ManyToManyField(blank=True, help_text="Employees assigned to cover during leave", related_name="covering_leaves", to="api.employee"),
        ),
    ]
