# Generated by Django 6.0 on 2026-01-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_asset_purchaserequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="event_type",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient", "-created_at"], name="api_notific_recipie_5c719b_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient", "is_read", "-created_at"], name="api_notific_recipie_0f27ac_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient", "is_archived"], name="api_notific_recipie_97a96d_idx"),
        ),
    ]
