# Generated by Django 6.0 on 2026-01-15 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_notification_optimization"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskSubtask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("completed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="completed_subtasks", to="api.employee")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="created_subtasks", to="api.employee")),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subtasks", to="api.calendarevent")),
            ],
            options={
                "db_table": "task_subtasks",
                "ordering": ["order", "created_at"],
                "indexes": [models.Index(fields=["task", "order"], name="task_subtas_task_id_e8f2e1_idx"), models.Index(fields=["is_completed"], name="task_subtas_is_comp_73c92f_idx")],
            },
        ),
    ]
