# Generated by Django 6.0 on 2026-01-15 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_tasksubtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="actual_hours",
            field=models.DecimalField(decimal_places=2, default=0, help_text="Total actual hours logged for this task", max_digits=8),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="estimated_hours",
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Estimated hours to complete the task", max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name="TaskTimeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, help_text="What was worked on")),
                ("started_at", models.DateTimeField(help_text="When the work started")),
                ("ended_at", models.DateTimeField(blank=True, help_text="When the work ended (null if timer still running)", null=True)),
                ("duration_minutes", models.PositiveIntegerField(default=0, help_text="Duration in minutes (calculated from start/end or manual entry)")),
                ("is_running", models.BooleanField(default=False, help_text="Whether this is an active timer")),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="time_logs", to="api.employee")),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="time_logs", to="api.calendarevent")),
            ],
            options={
                "db_table": "task_time_logs",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(fields=["task", "started_at"], name="task_time_l_task_id_939d10_idx"),
                    models.Index(fields=["employee", "started_at"], name="task_time_l_employe_f100a8_idx"),
                    models.Index(fields=["is_running"], name="task_time_l_is_runn_43151a_idx"),
                ],
            },
        ),
    ]
