# Generated by Django 6.0 on 2026-01-15 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_calendarevent_actual_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskgroup",
            name="department",
            field=models.ForeignKey(blank=True, help_text="The department this group represents (if is_department_group=True)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name="task_group", to="api.department"),
        ),
        migrations.AddField(
            model_name="taskgroup",
            name="is_department_group",
            field=models.BooleanField(default=False, help_text="If true, this group was auto-generated from a department"),
        ),
        migrations.AddIndex(
            model_name="taskgroup",
            index=models.Index(fields=["is_department_group"], name="task_groups_is_depa_618cd1_idx"),
        ),
    ]
