# Generated by Django 6.0.2 on 2026-02-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_smb_multi_config_user_reports_release_notes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="userreport",
            new_name="user_report_report__9e4aff_idx",
            old_name="user_report_report__7c5e0e_idx",
        ),
        migrations.RenameIndex(
            model_name="userreport",
            new_name="user_report_status_219f15_idx",
            old_name="user_report_status_3a1b2c_idx",
        ),
        migrations.RenameIndex(
            model_name="userreport",
            new_name="user_report_reporte_02775f_idx",
            old_name="user_report_reporte_4d5e6f_idx",
        ),
        migrations.AddField(
            model_name="externaluser",
            name="preferred_language",
            field=models.CharField(default="en", help_text="User's preferred UI language (en, zh, id)", max_length=5),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="event_type",
            field=models.CharField(choices=[("holiday", "Holiday"), ("leave", "Leave"), ("meeting", "Meeting"), ("task", "Task")], db_index=True, default="task", max_length=20),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_id",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="useractivitylog",
            name="action",
            field=models.CharField(
                choices=[("login", "Login"), ("logout", "Logout"), ("create", "Create"), ("update", "Update"), ("delete", "Delete"), ("view", "View"), ("export", "Export"), ("page_view", "Page View"), ("import", "Import")],
                db_index=True,
                help_text="Type of action performed",
                max_length=20,
            ),
        ),
    ]
