# Generated by Django 6.0.2 on 2026-02-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_externaluser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="overtimerequest",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="overtimerequest",
            name="status_changed_by",
            field=models.CharField(blank=True, help_text="Username of the admin who last changed the status", max_length=150),
        ),
    ]
