# Generated by Django 6.0.2 on 2026-02-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_add_status_changed_by_rejected_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfiguration",
            name="tab_icon",
            field=models.FileField(blank=True, help_text="Custom browser tab icon (.ico, .svg, .png)", null=True, upload_to="system/"),
        ),
        migrations.AlterField(
            model_name="overtimerequest",
            name="status_changed_by",
            field=models.CharField(blank=True, help_text="Username of the user who last changed the status", max_length=150),
        ),
    ]
