# Generated by Django 6.0.2 on 2026-02-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0031_add_tab_icon_to_systemconfiguration"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient", "is_archived", "-created_at"], name="api_notific_recipie_b54540_idx"),
        ),
    ]
