# Generated by Django 6.0.2 on 2026-02-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0032_add_notification_archived_created_at_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="overtimerequest",
            name="status",
            field=models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], db_index=True, default="pending", max_length=20),
        ),
    ]
