# Generated by Django 6.0.2 on 2026-02-27 01:40

import hashlib

from django.db import migrations, models


def populate_token_hashes(apps, schema_editor):
    """Populate token_hash for existing UserSession rows."""
    UserSession = apps.get_model("api", "UserSession")
    for session in UserSession.objects.all():
        session.token_hash = hashlib.sha256(session.access_token.encode()).hexdigest()
        session.save(update_fields=["token_hash"])


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0034_overtimelimitconfig"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="externaluser",
            name="external_us_externa_f017d4_idx",
        ),
        migrations.RemoveIndex(
            model_name="externaluser",
            name="external_us_usernam_be0f70_idx",
        ),
        migrations.RemoveIndex(
            model_name="externaluser",
            name="external_us_worker__a9d14c_idx",
        ),
        migrations.AddField(
            model_name="usersession",
            name="token_hash",
            field=models.CharField(db_index=True, default="", max_length=64, unique=True),
        ),
        migrations.RunPython(populate_token_hashes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="overtimelimitconfig",
            name="recommended_monthly_hours",
            field=models.DecimalField(decimal_places=2, default=60, help_text="Advised monthly overtime warning threshold", max_digits=5),
        ),
        migrations.AlterField(
            model_name="overtimelimitconfig",
            name="recommended_weekly_hours",
            field=models.DecimalField(decimal_places=2, default=15, help_text="Advised weekly overtime warning threshold", max_digits=5),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="access_token",
            field=models.TextField(),
        ),
    ]
