# Generated by Django 6.0.2 on 2026-02-27 02:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0035_usersession_token_hash"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="employee",
            name="api_employe_emp_id_67cac0_idx",
        ),
    ]
