# Generated by Django 6.0.2 on 2026-02-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0036_remove_duplicate_emp_id_index_and_calendar_noop_save"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="emp_id",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
