# Generated by Django 6.0.2 on 2026-02-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0037_employee_emp_id_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaluser",
            name="is_ptb_admin",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
