# Generated by Django 6.0.2 on 2026-02-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0038_externaluser_is_ptb_admin_index"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="overtimelimitconfig",
            constraint=models.UniqueConstraint(condition=models.Q(("is_active", True)), fields=("is_active",), name="unique_active_overtime_limit_config"),
        ),
    ]
