# Generated by Django 6.0.2 on 2026-02-27 07:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0040_asset_notes_jsonfield"),
    ]

    operations = [
        migrations.RenameField(
            model_name="overtimelimitconfig",
            old_name="recommended_monthly_hours",
            new_name="advised_monthly_hours",
        ),
        migrations.RenameField(
            model_name="overtimelimitconfig",
            old_name="recommended_weekly_hours",
            new_name="advised_weekly_hours",
        ),
    ]
