# Generated by Django 6.0.2 on 2026-02-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0041_rename_recommended_monthly_hours_overtimelimitconfig_advised_monthly_hours_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(fields=["resource"], name="user_activi_resourc_4a19fd_idx"),
        ),
    ]
