# Generated by Django 6.0.2 on 2026-02-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0042_add_resource_index_to_useractivitylog"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(fields=["event_type", "start"], name="api_calenda_event_t_ffd31f_idx"),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(fields=["created_by", "start"], name="api_calenda_created_4e952d_idx"),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(fields=["start", "end"], name="api_calenda_start_00406e_idx"),
        ),
        migrations.AddIndex(
            model_name="overtimerequest",
            index=models.Index(fields=["employee", "request_date"], name="api_overtim_employe_09eb0c_idx"),
        ),
    ]
