# Generated by Django 6.0.2 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0043_add_performance_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="refresh_token",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
