"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

# Log CORS origins for debugging
import logging
import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Note: Celery app is imported in backend/__init__.py (the standard pattern).
# Avoid importing it here to prevent import-ordering side effects.

# Determine environment
ENVIRONMENT = os.environ.get("DJANGO_ENV", "development")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load appropriate .env file
env_file = BASE_DIR / ".env.staging"  # Default to staging
if ENVIRONMENT == "production":
    env_file = BASE_DIR / ".env.prod"
elif ENVIRONMENT == "staging":
    env_file = BASE_DIR / ".env.staging"
elif ENVIRONMENT == "development":
    env_file = BASE_DIR / ".env.dev"

if env_file.exists():
    load_dotenv(env_file, override=True)
else:
    # Fallback to generic .env file (never silently load staging credentials)
    fallback = BASE_DIR / ".env"
    if fallback.exists():
        load_dotenv(fallback, override=True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY environment variable is not set. Django cannot start without a valid SECRET_KEY. Set it in your .env file or environment.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "").split()

# Feature toggles
THROTTLING_ENABLED = os.environ.get("THROTTLING_ENABLED", "false").lower() == "true"
EXPORT_THROTTLE_RATE = os.environ.get("EXPORT_THROTTLE_RATE", "5/min")
QUERY_MONITORING = os.environ.get("QUERY_MONITORING", str(DEBUG)).lower() == "true"

# Silence security warnings for HTTP-only deployment (staging/development)
# These warnings are only relevant for HTTPS/SSL production deployments
if ENVIRONMENT != "production":
    SILENCED_SYSTEM_CHECKS = [
        "security.W004",  # SECURE_HSTS_SECONDS - Not needed for HTTP
        "security.W008",  # SECURE_SSL_REDIRECT - Not using HTTPS
        "security.W012",  # SESSION_COOKIE_SECURE - Not using HTTPS
        "security.W016",  # CSRF_COOKIE_SECURE - Not using HTTPS
        "security.W018",  # DEBUG=True - Acceptable for staging environment
        "security.W019",  # X_FRAME_OPTIONS - Using SAMEORIGIN for admin/swagger UI
    ]
else:
    SILENCED_SYSTEM_CHECKS = []


# Application definition

INSTALLED_APPS = [
    "daphne",  # Must be before django.contrib.staticfiles for ASGI
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "drf_yasg",
    "channels",
    "api",
]


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Custom middleware
    "api.middleware.PerformanceMonitoringMiddleware",
    "api.middleware.SecurityHeadersMiddleware",
    "api.middleware.AuditLoggingMiddleware",
]

ROOT_URLCONF = "backend.urls"

# CORS settings - Dynamic configuration for different environments
# Base CORS origins (development and local testing)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3333",
    "http://127.0.0.1:3333",
    "http://172.18.220.56:3333",
]

# Add additional CORS origins from environment variable (comma-separated)
# Example: CORS_ADDITIONAL_ORIGINS="http://192.168.1.100:3333,http://myapp.local:3333"
additional_origins = os.environ.get("CORS_ADDITIONAL_ORIGINS", "")
if additional_origins:
    CORS_ALLOWED_ORIGINS.extend([origin.strip() for origin in additional_origins.split(",") if origin.strip()])

logger = logging.getLogger(__name__)
logger.info(f"CORS Allowed Origins: {CORS_ALLOWED_ORIGINS}")

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CORS_ORIGIN_ALLOW_ALL = False  # Never allow all origins; use CORS_ALLOWED_ORIGINS whitelist

# REST Framework Configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "api.authentication.LocalJWTAuthentication",
        "api.authentication.ExternalJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "api.pagination.StandardPageNumberPagination",
    "PAGE_SIZE": 25,
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    # Temporarily disable custom versioning for swagger schema generation
    # 'DEFAULT_VERSIONING_CLASS': 'api.versioning.APIVersioning',
    "DEFAULT_VERSION": "1.0",
    "EXCEPTION_HANDLER": "api.handlers.custom_exception_handler",
}
# Throttling (enabled via THROTTLING_ENABLED toggle)
if THROTTLING_ENABLED:
    REST_FRAMEWORK.update(
        {
            "DEFAULT_THROTTLE_CLASSES": [
                "rest_framework.throttling.AnonRateThrottle",
                "rest_framework.throttling.UserRateThrottle",
                "rest_framework.throttling.ScopedRateThrottle",
            ],
            "DEFAULT_THROTTLE_RATES": {
                "anon": "100/day",
                "user": "1000/day",
                "export": EXPORT_THROTTLE_RATE,
            },
        }
    )
# Phase 2 note: Redis cache/SMB toggles to be added here when enabled (see plans/PHASE_2_DOCUMENTATION_PLAN.md)

# External Authentication API
EXTERNAL_API_URL = os.environ.get("EXTERNAL_API_URL", "http://172.18.220.56:9001")
EXTERNAL_API_TIMEOUT = int(os.environ.get("EXTERNAL_API_TIMEOUT", "5"))

# Simple JWT Settings for local authentication
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
}

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {"Basic": {"type": "basic"}, "Bearer": {"type": "apiKey", "name": "Authorization", "in": "header"}},
    "USE_SESSION_AUTH": False,
    "PERSIST_AUTH": True,
    "REFETCH_SCHEMA_WITH_AUTH": True,
    "REFETCH_SCHEMA_ON_LOGOUT": True,
    "DEFAULT_INFO": "backend.urls.schema_view",
}

REDOC_SETTINGS = {
    "LAZY_RENDERING": True,
    "HIDE_HOSTNAME": False,
    "EXPAND_RESPONSES": "200,201",
    "PATH_IN_MIDDLE": False,
}
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.environ.get("SQL_DATABASE", "ptb_ot"),
        "USER": os.environ.get("SQL_USER", ""),
        "PASSWORD": os.environ.get("SQL_PASSWORD", ""),
        "HOST": os.environ.get("SQL_HOST", ""),
        "PORT": os.environ.get("SQL_PORT", ""),
        # Reuse DB connections for up to 10 minutes instead of opening/closing per request.
        # This eliminates the TCP + TLS + auth overhead on every API call.
        "CONN_MAX_AGE": int(os.environ.get("DB_CONN_MAX_AGE", 600)),
        "CONN_HEALTH_CHECKS": True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Jakarta"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
_static_dir = BASE_DIR / "static"
STATICFILES_DIRS = [_static_dir] if _static_dir.is_dir() else []
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files settings
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "mediafiles"

# Security Headers (HTTP-only deployment, no SSL/HTTPS)
SECURE_SSL_REDIRECT = False  # False for HTTP-only
SESSION_COOKIE_SECURE = False  # False for HTTP-only
CSRF_COOKIE_SECURE = False  # False for HTTP-only
SECURE_HSTS_SECONDS = 0  # Disabled for HTTP-only
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "SAMEORIGIN"

if not DEBUG:
    # Additional production security settings
    # SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Only if using HTTPS
    # SECURE_HSTS_PRELOAD = True  # Only if using HTTPS
    pass

    # Rate Limiting
    # REST_FRAMEWORK = {
    #     'DEFAULT_THROTTLE_CLASSES': [
    #         'rest_framework.throttling.AnonRateThrottle',
    #         'rest_framework.throttling.UserRateThrottle'
    #     ],
    #     'DEFAULT_THROTTLE_RATES': {
    #         'anon': '100/day',
    #         'user': '1000/day'
    #     }
    # }

# Security settings
SECURE_CROSS_ORIGIN_OPENER_POLICY = None  # Disable COOP header

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# ============================================================================
# Celery Configuration
# ============================================================================
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://localhost:6379/1")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes

# ============================================================================
# Logging Configuration
# ============================================================================


# Determine log levels based on environment
# For staging/production: Use WARNING to reduce log volume
# For development: Use DEBUG/INFO for detailed logging
def get_log_level(default_level="INFO"):
    """
    Get log level from environment variable.

    Usage in .env files:
    - Development: LOG_LEVEL=DEBUG
    - Staging: LOG_LEVEL=WARNING  (recommended to reduce noise)
    - Production: LOG_LEVEL=WARNING

    Valid levels: DEBUG, INFO, WARNING, ERROR, CRITICAL
    """
    level = os.environ.get("LOG_LEVEL", default_level).upper()
    valid_levels = ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]
    return level if level in valid_levels else default_level


# Determine default log level based on environment
if ENVIRONMENT == "production":
    DEFAULT_LOG_LEVEL = "WARNING"
elif ENVIRONMENT == "staging":
    DEFAULT_LOG_LEVEL = "WARNING"  # Staging: WARNING to reduce noise
else:  # development
    DEFAULT_LOG_LEVEL = "DEBUG"  # Dev: DEBUG for detailed logging

# Get actual log level from environment or use default
LOG_LEVEL = get_log_level(DEFAULT_LOG_LEVEL)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {message}",
            "style": "{",
        },
        "json": {"()": "pythonjsonlogger.jsonlogger.JsonFormatter", "format": "%(asctime)s %(name)s %(levelname)s %(message)s"},
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {"level": "WARNING", "class": "logging.StreamHandler", "formatter": "simple"},
        "file": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs", "django.log"),
            "maxBytes": 1024 * 1024 * 10,  # 10 MB
            "backupCount": 10,
            "formatter": "verbose",
        },
        "celery_file": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs", "celery.log"),
            "maxBytes": 1024 * 1024 * 10,  # 10 MB
            "backupCount": 10,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "file"],
            "level": max(logging.WARNING, logging.getLevelName(LOG_LEVEL)),  # At least WARNING level
            "propagate": False,
        },
        "api": {
            "handlers": ["console", "file"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "celery": {
            "handlers": ["console", "celery_file"],
            "level": LOG_LEVEL,  # Celery logs at WARNING level to reduce noise
            "propagate": False,
        },
    },
}

logging.basicConfig(level=logging.INFO)
startup_logger = logging.getLogger(__name__)
startup_logger.info(f"✓ Logging configured: ENVIRONMENT={ENVIRONMENT}, LOG_LEVEL={LOG_LEVEL}")

# Create logs directory if it doesn't exist
os.makedirs(os.path.join(BASE_DIR, "logs"), exist_ok=True)

# ============================================================================
# Cache Configuration
# ============================================================================
# Configure Redis for caching (separate instance from Celery)
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("REDIS_CACHE_URL", "redis://localhost:6379/2"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 50,
                "retry_on_timeout": True,
            },
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            "IGNORE_EXCEPTIONS": True,  # Fail-open: return None if Redis unavailable
        },
    }
}


# ============================================================================
# SMB File Storage Configuration
# ============================================================================
def get_bool_env(key, default=False):
    """Convert environment variable to boolean"""
    value = os.getenv(key, str(default)).lower()
    return value in ("true", "1", "yes", "on")


SMB_CONFIG = {
    "enabled": get_bool_env("SMB_ENABLED", False),
    "server": os.getenv("SMB_SERVER", ""),
    "share": os.getenv("SMB_SHARE_NAME", "OvertimeReports"),
    "username": os.getenv("SMB_USERNAME", ""),
    "password": os.getenv("SMB_PASSWORD", ""),
    "domain": os.getenv("SMB_DOMAIN", "WORKGROUP"),
    "port": int(os.getenv("SMB_PORT", "445")),
    "path_prefix": os.getenv("SMB_PATH_PREFIX", "Management\\PTB\\AST_Portal_Overtime\\"),
    "timeout": int(os.getenv("SMB_TIMEOUT", "30")),
}

SMB_POOL_SIZE = {
    "min": int(os.getenv("SMB_POOL_MIN_SIZE", "2")),
    "max": int(os.getenv("SMB_POOL_MAX_SIZE", "5")),
}

# ============================================================================
# Django Channels (WebSocket Support for Task Board)
# ============================================================================
ASGI_APPLICATION = "backend.asgi.application"

# Channel Layers - Use Redis when available (required for reliable WebSocket delivery)
# Auto-detect: USE_REDIS_CHANNELS=true OR CELERY_BROKER_URL contains "redis"
_use_redis_channels = os.environ.get("USE_REDIS_CHANNELS", "").lower() == "true" or "redis" in CELERY_BROKER_URL
if _use_redis_channels:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [os.environ.get("REDIS_CHANNELS_URL", "redis://localhost:6379/3")],
                "capacity": 1500,
                "expiry": 10,
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }
